import type { Section } from "./types";

export const BASE_SECTIONS: Record<string, Omit<Section, "id">> = {
  hero: {
    name: "ヒーロー",
    purpose: "3秒以内に「自分ごと」だと感じさせる",
    content: "キャッチコピー、サブコピー、メインCTA、キービジュアル",
    reason: "離脱の50%はファーストビューで起きる。最初に価値提案を置く",
    headline: "",
  },
  pain: {
    name: "課題提起",
    purpose: "訪問者の悩みを言語化し、共感を生む",
    content: "よくある悩み3〜5個、共感コピー",
    reason: "「わかってくれている」と感じさせることで離脱を防ぐ",
    headline: "",
  },
  solution: {
    name: "解決策",
    purpose: "課題に対する解決策としてサービスを提示",
    content: "サービス概要、ビフォーアフター、解決の仕組み",
    reason: "課題提起の直後に解決策を出すと、論理的な流れで納得感が生まれる",
    headline: "",
  },
  features: {
    name: "特徴・強み",
    purpose: "競合との差別化ポイントを明確にする",
    content: "3〜4つの特徴、アイコン+説明文、データや実績",
    reason: "解決策の具体性を補強し、「なぜこのサービスか」に答える",
    headline: "",
  },
  howItWorks: {
    name: "利用の流れ",
    purpose: "申込から利用開始までの不安を取り除く",
    content: "3〜5ステップ、番号付きフロー、所要時間",
    reason: "手順が見えると心理的ハードルが下がる",
    headline: "",
  },
  pricing: {
    name: "料金プラン",
    purpose: "価格の納得感を作る",
    content: "プラン比較表、含まれるもの、お得感の演出",
    reason: "価格は必ず確認される。隠すと不信感が生まれる",
    headline: "",
  },
  testimonials: {
    name: "お客様の声",
    purpose: "第三者の評価で信頼を補強する",
    content: "顔写真+名前+感想、具体的な数字（Before/After）",
    reason: "自社の主張より顧客の声の方が3倍信頼される（Nielsen調査）",
    headline: "",
  },
  casestudy: {
    name: "導入事例",
    purpose: "具体的な成果を示し、自分ごと化させる",
    content: "企業名、課題、導入後の成果、担当者コメント",
    reason: "BtoBでは事例が意思決定の最大要因。具体性が信頼に直結する",
    headline: "",
  },
  faq: {
    name: "よくある質問",
    purpose: "残っている不安・疑問を潰す",
    content: "5〜8問のQ&A、返金・解約・サポートに関する質問",
    reason: "CTAの直前に置くことで、最後の躊躇を解消する",
    headline: "",
  },
  cta: {
    name: "CTA（行動喚起）",
    purpose: "具体的な次のアクションを促す",
    content: "CTAボタン、行動を後押しするコピー、特典・限定感",
    reason: "LPの最終目標。全セクションはここへの導線",
    headline: "",
  },
  gallery: {
    name: "ギャラリー",
    purpose: "視覚的に雰囲気や品質を伝える",
    content: "写真4〜8枚、スライダーまたはグリッド",
    reason: "言葉だけでは伝わらない体験価値を写真で補完する",
    headline: "",
  },
  team: {
    name: "スタッフ紹介",
    purpose: "人の顔を見せることで親近感と信頼を生む",
    content: "顔写真、名前、資格・経歴、一言メッセージ",
    reason: "「誰がやるか」が見えるとサービスの信頼度が上がる",
    headline: "",
  },
  comparison: {
    name: "他社比較",
    purpose: "競合と比較して優位性を視覚的に示す",
    content: "比較表（自社 vs 一般的なサービス）、チェックマーク",
    reason: "比較検討中のユーザーに判断材料を提供し、離脱を防ぐ",
    headline: "",
  },
  guarantee: {
    name: "保証・安心",
    purpose: "リスクを取り除いて行動を促す",
    content: "返金保証、無料期間、サポート体制、セキュリティ",
    reason: "リスクリバーサルは購入率を最大20%上げる",
    headline: "",
  },
  access: {
    name: "アクセス",
    purpose: "来店型サービスの物理的な情報を提供",
    content: "地図、住所、営業時間、駐車場情報",
    reason: "来店型では場所が意思決定の重要要素",
    headline: "",
  },
  menu: {
    name: "メニュー一覧",
    purpose: "提供内容と価格を一覧で見せる",
    content: "サービス名、説明、価格、所要時間",
    reason: "選択肢が見えると具体的な検討に進みやすい",
    headline: "",
  },
  demo: {
    name: "デモ",
    purpose: "実際の使用感をイメージさせる",
    content: "スクリーンショット、動画、インタラクティブデモ",
    reason: "SaaS/ツール系では「触れる感覚」が意思決定を加速する",
    headline: "",
  },
  stats: {
    name: "実績・数字",
    purpose: "具体的な数字でスケールと信頼性を示す",
    content: "導入社数、利用者数、満足度、継続率",
    reason: "数字は抽象的な主張に具体性を与え、信頼度を高める",
    headline: "",
  },
  media: {
    name: "メディア掲載",
    purpose: "第三者メディアの権威を借りて信頼を高める",
    content: "掲載メディアのロゴ、記事タイトル、掲載日",
    reason: "権威バイアスを活用。知名度のあるメディアほど効果が高い",
    headline: "",
  },
  recruitment: {
    name: "募集要項",
    purpose: "応募に必要な情報を明確に提示",
    content: "職種、条件、給与、勤務地、福利厚生",
    reason: "採用LPでは条件の透明性が応募率に直結する",
    headline: "",
  },
  culture: {
    name: "社風・カルチャー",
    purpose: "働く環境や雰囲気を伝え、応募の動機づけをする",
    content: "オフィス写真、社員インタビュー、価値観",
    reason: "ミスマッチ防止と動機づけの両面で効果がある",
    headline: "",
  },
};
